import { For, Show } from "solid-js";
import type { JSX } from "@solidjs/web";
import type { EffectDescriptor, ParamSpec } from "~/types/contract";
import { COLOR_PATTERN } from "~/types/contract";

/**
 * Props for `<ParamsForm>`.
 */
export interface ParamsFormProps {
  /** The chosen effect. Its `params` array decides which inputs appear. */
  descriptor: EffectDescriptor;
  /** The **complete** current values (defaults already merged in). */
  values: Record<string, unknown>;
  /** Called with the new complete value set whenever any single input changes. */
  onChange(next: Record<string, unknown>): void;
  /** Field-level messages from a `VALIDATION_FAILED` response, keyed by `ParamSpec.key`. */
  issues?: Record<string, string>;
}

/**
 * Renders the parameter form for whichever effect is selected.
 *
 * Nothing here is specific to any effect: the form is generated by walking
 * `descriptor.params` and switching on each `ParamSpec.kind`. Adding a new knob to an effect
 * therefore needs no change in the admin UI at all — that is the whole point of `ParamSpec`.
 */
export function ParamsForm(props: ParamsFormProps): JSX.Element {
  /** Replaces one key and hands the caller a fresh complete object (never mutating in place). */
  const set = (key: string, value: unknown) => {
    props.onChange({ ...props.values, [key]: value });
  };

  return (
    <Show
      when={props.descriptor.params.length > 0}
      fallback={<p class="faint">This effect has no configurable parameters.</p>}
    >
      <For each={props.descriptor.params}>
        {(spec) => (
          <div class="field">
            <label class="field-label" for={`param-${spec.key}`}>
              {spec.label}
            </label>
            {renderInput(spec, props.values[spec.key], (v) => set(spec.key, v))}
            <Show when={spec.description}>
              <p class="field-help">{spec.description}</p>
            </Show>
            <Show when={props.issues?.[spec.key]}>
              {(message) => <p class="field-error">{message()}</p>}
            </Show>
          </div>
        )}
      </For>
    </Show>
  );
}

/** Picks the right input element for one parameter and wires it to `onValue`. */
function renderInput(
  spec: ParamSpec,
  value: unknown,
  onValue: (next: unknown) => void,
): JSX.Element {
  switch (spec.kind) {
    case "number":
      return <NumberInput spec={spec} value={value} onValue={onValue} />;
    case "color":
      return <ColorInput spec={spec} value={value} onValue={onValue} />;
    case "boolean":
      return <BooleanInput spec={spec} value={value} onValue={onValue} />;
    case "select":
      return <SelectInput spec={spec} value={value} onValue={onValue} />;
    case "text":
    default:
      return <TextInput spec={spec} value={value} onValue={onValue} />;
  }
}

/** Shared shape of the small input components below. */
interface InputProps {
  spec: ParamSpec;
  value: unknown;
  onValue(next: unknown): void;
}

/**
 * A number parameter.
 *
 * When the spec declares both `min` and `max` this is a slider plus a number box showing the exact
 * value, because dragging is the natural way to tune a visual effect while watching the preview.
 * Without bounds a slider has nothing to slide between, so it falls back to a plain number box.
 */
function NumberInput(props: InputProps): JSX.Element {
  const fallback = () => (typeof props.spec.default === "number" ? props.spec.default : 0);
  const current = () => (typeof props.value === "number" ? props.value : fallback());
  const bounded = () => props.spec.min !== undefined && props.spec.max !== undefined;
  const step = () => props.spec.step ?? 0.01;

  /** Keeps the value inside the declared range so the backend never rejects it. */
  const clamp = (n: number): number => {
    let out = n;
    if (props.spec.min !== undefined) out = Math.max(props.spec.min, out);
    if (props.spec.max !== undefined) out = Math.min(props.spec.max, out);
    return out;
  };

  const commit = (raw: string) => {
    const parsed = Number(raw);
    props.onValue(Number.isFinite(parsed) ? clamp(parsed) : fallback());
  };

  return (
    <Show
      when={bounded()}
      fallback={
        <input
          id={`param-${props.spec.key}`}
          type="number"
          step={step()}
          value={current()}
          onInput={(e) => commit(e.currentTarget.value)}
        />
      }
    >
      <div class="slider-row">
        <input
          id={`param-${props.spec.key}`}
          type="range"
          min={props.spec.min}
          max={props.spec.max}
          step={step()}
          value={current()}
          onInput={(e) => commit(e.currentTarget.value)}
        />
        <input
          class="slider-value"
          type="number"
          min={props.spec.min}
          max={props.spec.max}
          step={step()}
          value={current()}
          onInput={(e) => commit(e.currentTarget.value)}
        />
      </div>
    </Show>
  );
}

/**
 * A color parameter.
 *
 * Two inputs bound to the same value: the operating system's color picker for choosing visually,
 * and a text box so a hex code can be pasted from a brand palette. The contract requires the
 * `#rrggbb` form, so the text box is validated against exactly that pattern.
 */
function ColorInput(props: InputProps): JSX.Element {
  const fallback = () =>
    typeof props.spec.default === "string" && COLOR_PATTERN.test(props.spec.default)
      ? props.spec.default
      : "#ffffff";
  const raw = () => (typeof props.value === "string" ? props.value : fallback());
  const valid = () => COLOR_PATTERN.test(raw());

  return (
    <div class="color-row">
      <input
        type="color"
        aria-label={`${props.spec.label} colour picker`}
        value={valid() ? raw() : fallback()}
        onInput={(e) => props.onValue(e.currentTarget.value)}
      />
      <input
        id={`param-${props.spec.key}`}
        type="text"
        class={valid() ? undefined : "invalid"}
        spellcheck={false}
        value={raw()}
        placeholder="#rrggbb"
        onInput={(e) => props.onValue(e.currentTarget.value)}
      />
    </div>
  );
}

/** A boolean parameter: one checkbox with its label to the right. */
function BooleanInput(props: InputProps): JSX.Element {
  const checked = () =>
    typeof props.value === "boolean" ? props.value : props.spec.default === true;
  return (
    <label class="checkbox-row">
      <input
        id={`param-${props.spec.key}`}
        type="checkbox"
        checked={checked()}
        onChange={(e) => props.onValue(e.currentTarget.checked)}
      />
      <span class="muted">{checked() ? "On" : "Off"}</span>
    </label>
  );
}

/** A select parameter: a dropdown limited to the spec's `options`. */
function SelectInput(props: InputProps): JSX.Element {
  const options = () => props.spec.options ?? [];
  const current = () => {
    const value = typeof props.value === "string" ? props.value : "";
    if (options().includes(value)) return value;
    const fallback = typeof props.spec.default === "string" ? props.spec.default : "";
    return options().includes(fallback) ? fallback : (options()[0] ?? "");
  };

  return (
    <Show
      when={options().length > 0}
      fallback={<p class="field-error">This "select" parameter declares no options.</p>}
    >
      <select
        id={`param-${props.spec.key}`}
        value={current()}
        onChange={(e) => props.onValue(e.currentTarget.value)}
      >
        <For each={options()}>{(option) => <option value={option}>{option}</option>}</For>
      </select>
    </Show>
  );
}

/** A free-text parameter. The contract caps these at 1024 characters. */
function TextInput(props: InputProps): JSX.Element {
  const current = () =>
    typeof props.value === "string"
      ? props.value
      : typeof props.spec.default === "string"
        ? props.spec.default
        : "";
  return (
    <input
      id={`param-${props.spec.key}`}
      type="text"
      maxlength={1024}
      value={current()}
      onInput={(e) => props.onValue(e.currentTarget.value)}
    />
  );
}
